name: zive

on:
  push:
    branches: [ main ]

env:
  NUNIT_VERSION: 3.12.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Nunit/zive/zive.csproj


    - name: Build solution
      run: dotnet build --configuration Release Nunit/zive/zive.csproj

    - name: Test with NUnit
      run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover Nunit/zive/zive.csproj

      env:
        NUNIT_EXE: ./tools/nunit3-console.exe


