name: zive mstest
on:
  push:
    branches: [main]

env:
  MSTEST_VERSION: 2.1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore MSTest/zive/zive.csproj

    - name: Build solution
      run: dotnet build --configuration Release MSTest/zive/zive.csproj

    - name: Test with MSTest
      run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover MSTest/zive/zive.csproj

      env:
        MSTEST_EXE: ./tools/mstest.exe

